[project]
name = "abc"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "jsonschema>=4.25.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "rich>=14.1.0",
    "tenacity>=9.1.2",
]
